python:
  - 2.7
  - 3.7      # [not arm64]
  - 3.8
  - 3.9
numpy:
  - 1.16
  # python 3.7-3.9
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]