{% set version = "4.0.1" %}

package:
  name: pymongo
  version: {{ version }}

source:
  fn: pymongo-{{ version }}.tar.gz
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: 5be2736b55d52fef24c261032fa87b11c52b5d213cde9bea10316007aac3665e

build:
  number: 0
  # Skip s390x due to missing mongodb in s390x
  skip: True  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:  # [osx]
    - TRAVIS   # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  files:  # [linux and not (s390x or ppc64le)]
    - run_the_tests.sh   # [linux and not (s390x or ppc64le)]
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - mongodb     # [linux and not (s390x or ppc64le)]
    - pip
    - setuptools
  commands:
    - bash run_the_tests.sh  # [linux and not (s390x or ppc64le)]
    - pip check

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python driver for MongoDB http://www.mongodb.org
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: https://pymongo.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
