{% set version = "4.0" %}

package:
  name: pymongo
  version: {{ version }}

source:
  fn: pymongo-{{ version }}.tar.gz
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: b01372667bc2db7f45fd1c17bb66deb6cf7ff904c052c43af71b2173a9d7e82a

build:
  number: 0
  # skip s390x due to missing mongodb in s390x
  skip: True  # [s390x]
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:  # [osx]
    - TRAVIS   # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  files:  # [linux and not (s390x or aarch64 or ppc64le)]
    - run_the_tests.sh   # [linux and not (s390x or aarch64 or ppc64le)]
  imports:
    - bson
    - gridfs
    - pymongo
  requires:  # [not win]
    - mongodb  # [not win]
    - setuptools  # [not win]
    - pip         #[not win]
  commands:
    - bash run_the_tests.sh  # [linux and not (s390x or aarch64 or ppc64le)]
    - pip check  #[not win]

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python driver for MongoDB http://www.mongodb.org
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: https://pymongo.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
