{% set version = "4.8.0" %}

package:
  name: pymongo
  version: {{ version }}

source:
  fn: pymongo-{{ version }}.tar.gz
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: 3639d459b06257b529c5675bb68e0f89d4a4d77fe5f76c01107202c3ba52d4cb
  patches:
    - patches/0001-generate-normalized-platform-tag.patch

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  ignore_run_exports:
    - python
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools >=65.0
    - hatchling # >1.24
    - hatch-requirements-txt >=0.4.1
  run:
    - python
    - dnspython >=1.16.0,<3.0.0
  run_constrained:
    - pymongo-auth-aws >=1.1.0,<2.0.0
    - pymongocrypt >=1.6.0,<2.0.0
    - certifi             # [win or osx]
    - pykerberos          # [not win]
    - winkerberos >=0.5.0 # [win]
    - pyopenssl >=17.2.0
    - requests <3.0.0
    - cryptography >=2.5
    - service_identity >=18.1.0
    - python-snappy
    - zstandard

{% set tests_to_ignore = "" %}
# It is now a ConfigurationError to not have pymongo_auth_aws
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/auth_aws/test_auth_aws.py" %}
# pymongo.errors.ServerSelectionTimeoutError
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/mod_wsgi_test/mod_wsgi_test.py" %}
# We don't have the test/performance/data files
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/performance/perf_test.py" %}
# We don't have a mongodb instance
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/auth_oidc/test_auth_oidc.py" %}
# We don't have an atlas instance (mongodb in the cloud)
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/atlas/test_connection.py" %}
# We don't have an OCSP instance (Online Certificate Status Protocol)
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/ocsp/test_ocsp.py" %}

# No mockupdb for s390x
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/mockupdb" %}  # [s390x]

{% set tests_to_skip = "" %}
# The test is expecting to be running under  kubernetes?
{% set tests_to_skip = tests_to_skip + "test_container_metadata" %}
# A less than obvious AssertionError
{% set tests_to_skip = tests_to_skip + " or test_metadata" %}
# AssertionError (got nothing)
{% set tests_to_skip = tests_to_skip + " or test_initial_ismaster" %}  # [win-64 or (osx and x86)]


test:
  source_files:
    - test
    - mypy_test.ini
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - pip
    - pytest >=7
    - mockupdb  # [not s390x]
  commands:
    - pip check
    - pytest -v . {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"

about:
  home: https://www.mongodb.org
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python driver for MongoDB http://www.mongodb.org
  description: |
    The PyMongo distribution contains tools for interacting with MongoDB 
    database from Python. The bson package is an implementation of the 
    BSON format for Python. The pymongo package is a native Python driver 
    for MongoDB. The gridfs package is a gridfs implementation on top of pymongo.
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: https://pymongo.readthedocs.io

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
