{% set name = "pymongo" %}
{% set version = "4.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: cb6490e009b8f8dcc12b074774dd3673c0d721fabcfbe8c93db9e4a4ed017162

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - hatchling >1.24
    - hatch-requirements-txt >=0.4.1
    - setuptools >=65.0
  run:
    - python
    - dnspython <3.0.0,>=1.16.0
  run_constrained:
    - pymongo-auth-aws >=1.1.0,<2.0.0
    - pymongocrypt >=1.13.0,<2.0.0
    - winkerberos >=0.5.0  # [win]
    - pyopenssl >=17.2.0
    - requests <3.0.0
    - cryptography >=2.5
    - service_identity >=18.1.0

test:
  source_files:
    - test
    - pyproject.toml
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - pip
    - pytest >=8.2
    - mockupdb
    - pytest-asyncio >=0.24.0
  commands:
    - pip check
    - pytest -v test
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://www.mongodb.org
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: PyMongo - the Official MongoDB Python driver
  description: |
    The PyMongo distribution contains tools for interacting with MongoDB
    database from Python. The bson package is an implementation of the
    BSON format for Python. The pymongo package is a native Python driver
    for MongoDB. The gridfs package is a gridfs implementation on top of pymongo.
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: https://www.mongodb.com/docs/languages/python/pymongo-driver/current

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
