{% set version = "3.11.2" %}

package:
  name: pymongo
  version: {{ version }}

source:
  fn: pymongo-{{ version }}.tar.gz
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: 3710db69ad96f111797b0cb2c16fb44c8b65a27eccd096daeb9d9b963007bdde

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:  # [osx]
    - TRAVIS   # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  imports:
    - bson
    - gridfs
    - pymongo
  requires:  # [not win]
    - mongodb  # [not win]
    - setuptools  # [not win]

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache 2.0
  license_file: LICENSE
  summary: Python driver for MongoDB http://www.mongodb.org

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
