{% set version = "4.6.3" %}

package:
  name: pymongo
  version: {{ version }}

source:
  fn: pymongo-{{ version }}.tar.gz
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: c3b1be222869a35fee67714b754ebe8c5e83553b34ec60a6e8870ba0ea4f4496

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - dnspython >=1.16.0,<3.0.0

test:
  source_files:
    - .
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - setuptools
    - pip
    - pytest
  commands:
    - pytest .
    - pip check

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python driver for MongoDB http://www.mongodb.org
  description: |
    The PyMongo distribution contains tools for interacting with MongoDB 
    database from Python. The bson package is an implementation of the 
    BSON format for Python. The pymongo package is a native Python driver 
    for MongoDB. The gridfs package is a gridfs implementation on top of pymongo.
  dev_url: https://github.com/mongodb/mongo-python-driver
  doc_url: https://pymongo.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - licode
    - jakirkham
    - tacaswell
    - CJ-Wright
