travis:
  secure:
    BINSTAR_TOKEN: R0RwtQLbik0iI2oF0UvK+DsnVIFd9+0P1a0JHAnat1lcrHltn9DbJaUWq3y4G3apgteUY7JfBj7iNiNwzm3uCmoBaOEaNtA3jGxrhVmy0xFxjDthmMRm5hDtPJd0hTK2XPCAVEqoFFWGRYQ60cYMko0j8ICl2o0/kYs7vuBAkuKv0rE25pW83Mq9g4iJFy3WOsGRiYZTG1T2DLJp7wNR2BH4YOkdaE6ygEqrb+M8gV5rgdvz+8rinSdZyhfNnazl5jrKRxXt3aU59RIGV+M3wcImHB2/muJRlbOROImtwzAB7UFkheYOSff9N59MhVp0IUivNwPjZa/f0qL6bZgN6lvdFjuUyYlRnhZsEib6WMHAU7IHvKA2sZsAWdyVeXfRKL910CByxsJ5pu4st15C3IOt6foGEhAaEkHtLgvy+VxT7nnmc6kCZry/RqnASgCfkuSb7MokpGt/6ym3lDwcFeQrS0uRvjsgJFi5nnINihiUpP3L90ySKCbPBqpxm4dqBd+cuZN/iaokf6g4EqIIUvEPbOv5rSjuU2Qauf60RwrSkL6xzVj15pQYpu9vAtMIELVyRY5Y+WxEJli0KKBsOZN5uS0UNT+3OgBtgI8B9cB75lNXn0ROFdiJYifFq91UdeVGhWQt2KqTum/W3+bxccQSGlffQm9n/U3M/xSCnZM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
