travis:
  secure:
    BINSTAR_TOKEN: z8MMVRYJit2xwMs3uLYEE8a3/kTeYa8+Mn47il0Ss6yGj+BqMDyZBBnPTYUGrixtseNe2KX2BGKze8UkSYuyQSMFj5HJTDz26SvyXHxFNZjPL2ixg4hVKZxKJ6x96+gRHGA5s7QRTWSszlFwNvcS4YPjBjGmYGBAOqByWa+6P4OJQd+jjQ0W+iXg+SNANRy2Efwj+4sHKCAFO5LJw8Vp6QWNrGdieepkxTpJOoioW578x1t2AkYO15JxIH0A8BDFzcnY4tpMc7QGOJBtkekB6ElypqplUS+XAETPow+ry/kfcyauHHTjpqjuGcwb2XFnS+UcWNBe73Uhrese5yP63ppwmM1puhvG/p0JLJKlsFoNe627SY6logebGMqsL1MKm4eol5p0N6lOaAsa3WfzZdwhHnkbtEDybx/ZJYZ0He5MTCiO9wwzkHbGwpUSqATwoV7QAOfPldhvX+PR/h4vrqcddZc7ISqfTRfRQ5aaZV3d/9BaIefs2n8sShgcT/S1cnhNKb91MkyNOgIFgqE6EpVsyZBIry6ffejU1xz+4H8G0tZXHtgbRJ32ChKYYEzQPSeF0Kd4nhuIcDe338WnkvbPyFbJIyKQAplepW55tY6rcGdCo91pKg/jvhoEMft082SxKH7mlmwlbzUyG69m2Nd3vHD/cSY03i7W2tegOQw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
